name: Cross Compile for ARM64 on OpenWRT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up cross-compilation toolchain for ARM64
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Clone OpenWRT SDK
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Set up OpenWRT build environment
      run: |
        cd openwrt
        make defconfig
        make menuconfig

    - name: Build application for ARM64
      run: |
        cd openwrt
        # 设置交叉编译目标
        make package/feeds/packages/your-package-name/compile

    - name: Archive ARM64 build output
      uses: actions/upload-artifact@v3
      with:
        name: arm64-build
        path: ./openwrt/bin/targets
